# Load external shell dependencies.

autoload -U compinit

# Set shell configuration options.
setopt autocd             # Change working directory without cd command
setopt histignoredups     # Don't save duplicate lines in the history
setopt magicequalsubst    # Allow tab-completion after equals sign
setopt noautomenu         # Don't cycle through tab-completion options
setopt noautoremoveslash  # Keep trailing slash after tab completion
bindkey -v                # Vi line editing mode

# Initialize shell completion system.
compinit -d ~/.cache/zsh/zcompdump
zstyle ":completion:*:default" list-colors ${(s.:.)LS_COLORS}

# Configure key bindings.
bindkey -M viins "^[[H"    beginning-of-line
bindkey -M vicmd "^[[H"    beginning-of-line
bindkey -M viins "^[[1~"   beginning-of-line
bindkey -M vicmd "^[[1~"   beginning-of-line
bindkey -M viins "^[[F"    end-of-line
bindkey -M vicmd "^[[F"    end-of-line
bindkey -M viins "^[[4~"   end-of-line
bindkey -M vicmd "^[[4~"   end-of-line
bindkey -M viins "^[[1;5D" backward-word
bindkey -M vicmd "^[[1;5D" backward-word
bindkey -M viins "^[[1;5C" forward-word
bindkey -M vicmd "^[[1;5C" forward-word
bindkey -M viins "^[[3~"   delete-char
bindkey -M vicmd "^[[3~"   delete-char
bindkey -M viins "^?"      backward-delete-char
bindkey -M viins "^W"      backward-kill-word
bindkey -M viins "^U"      backward-kill-line
bindkey -M viins "^K"      up-history
bindkey -M viins "^J"      down-history
bindkey -M viins "^R"      history-incremental-search-backward
bindkey -M viins "^F"      history-incremental-search-forward
bindkey -M viins "^i"      expand-or-complete-prefix

# Set non-exported shell variables.
HISTFILE="$HOME/.cache/zsh/history"
HISTSIZE="10000"
SAVEHIST="10000"
WORDCHARS=${WORDCHARS/\//}

# Set prompt prefix with optional user/host.
[[ "$USER" != "jay" && "$USER" != "jcornwal" ]] && PS1PREFIX="$USER"
[[ -n "$SSH_CLIENT" || -n "$PS1PREFIX" ]] && PS1PREFIX="$PS1PREFIX@%m"

PS1=""
if [[ -n "$PS1PREFIX" ]]; then
  PS1="%F{20}%K{18} $PS1PREFIX %F{18}%K{19}"
fi
PS1="$PS1%K{19}%F{20} %1~ %k%F{19}%f "

# Define command aliases.
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias c="cd"
alias cp="cp -i"
alias e="nvim"
alias gdb="gdb -nh -x ~/.config/gdb/init"
alias grep="grep --color"
alias l="ls"
alias la="ls --color -la"
alias ll="ls --color -l"
alias ls="ls --color"
alias mv="mv -i"
alias o="xdg-open &>/dev/null"
alias rm="rm -i"
alias s="sudo "
alias t="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias ta="tmux attach"
alias vim="nvim"
alias wget="wget --no-hsts"
